cors: 
  originPatterns: http://localhost:3000,https://signature.com.br

file:
  upload-dir: /home/desenvolvimento/uploadDier
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://172.18.0.3:5432/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: pguser
    password: pgpassword
  jpa:
    hibernate:
      ddl-auto: none   
    database: POSTGRESQL
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
        

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  pathsToMatch: 
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true

      